#!/usr/bin/env bash
# One-time setup for the system-test harness, inside WSL.
#
#   wsl -d Ubuntu -u root -- bash /mnt/c/GitProjects/printer-server/tests/scripts/bootstrap.sh
#
# Installs what the harness needs and is not already present, then generates
# tests/.env.local with fresh secrets. Idempotent: safe to re-run, and it never
# overwrites an existing .env.local (that file may hold your AWS keys).
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
need_root

WITH_MINIO=1
while (($#)); do
  case "$1" in
    --no-minio) WITH_MINIO=0 ;;
    -h|--help) echo "usage: bootstrap.sh [--no-minio]"; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
  shift
done

# ---------------------------------------------------------------------------
# 1. Node + Newman.
#
# The whole harness runs inside WSL rather than driving the gateway from
# Windows. Two reasons, both discovered the hard way: wslrelay's Windows->WSL
# port forwarding on this box accepts the connection and then delivers nothing,
# and the secure profiles bind 127.0.0.1 only — which by design can ONLY be
# reached by a client on the same host. A Windows-side runner would therefore
# have to weaken the very posture the tests exist to verify.
# ---------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  say "installing nodejs + npm (needed for newman)"
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq nodejs npm >/dev/null
fi
note "node $(node -v)"

if ! command -v newman >/dev/null 2>&1; then
  say "installing newman"
  npm install -g newman >/dev/null 2>&1 || die "npm install -g newman failed"
fi
note "newman $(newman --version)"

# ---------------------------------------------------------------------------
# 2. Odds and ends the scripts use
# ---------------------------------------------------------------------------
for pkg in curl python3; do
  command -v "$pkg" >/dev/null 2>&1 || {
    say "installing $pkg"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$pkg" >/dev/null
  }
done

# ---------------------------------------------------------------------------
# 3. MinIO (local backend). Not in apt; the single static binary is the
#    upstream-recommended install and needs no container runtime, which keeps
#    the local backend working whether or not Docker Desktop is up.
# ---------------------------------------------------------------------------
if ((WITH_MINIO)) && [[ ! -x /usr/local/bin/minio ]]; then
  say "downloading minio server"
  curl -fsSL -o /usr/local/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio \
    || die "minio download failed (no egress? re-run with --no-minio and use --backend internal|aws)"
  chmod +x /usr/local/bin/minio
fi
if ((WITH_MINIO)) && [[ ! -x /usr/local/bin/mc ]]; then
  say "downloading minio client (mc)"
  curl -fsSL -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc \
    || die "mc download failed"
  chmod +x /usr/local/bin/mc
fi

# ---------------------------------------------------------------------------
# 4. Secrets. Generated once into tests/.env.local (git-ignored) so no real
#    token ever enters the repository — the live systemd unit currently carries
#    one inline in Environment=, which this harness replaces.
# ---------------------------------------------------------------------------
gen() { head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 32; }

if [[ -f "$ENV_LOCAL" ]]; then
  note "$ENV_LOCAL exists — left untouched"
else
  say "generating $ENV_LOCAL"
  cat > "$ENV_LOCAL" <<EOF
# GENERATED by tests/scripts/bootstrap.sh — git-ignored, never commit.
# Secrets used by the system-test harness only.

# The shared print token for the env-sourced profiles (A, C, E, F, G).
GW_TOKEN=$(gen)

# The token seeded INTO Vault for profiles B and D. Deliberately different from
# GW_TOKEN: profile B sets PRINT_GATEWAY_TOKEN=\${GW_ALT_TOKEN} and expects
# Vault to win, so the two values must be distinguishable for GW-SEC-02a/b to
# mean anything.
GW_VAULT_TOKEN=$(gen)

# ---- internal MinIO (backend "internal") — fill in to enable profile C/D there
#S3_INTERNAL_ENDPOINT=minio.internal.example:9000
#S3_INTERNAL_BUCKET=printgw-test
#S3_INTERNAL_REGION=us-east-1
#S3_INTERNAL_INSECURE=false
#S3_INTERNAL_ACCESS_KEY=
#S3_INTERNAL_SECRET_KEY=

# ---- real AWS S3 (backend "aws") — needs s3:GetObject/s3:PutObject on the bucket.
# Endpoint form matters: minio-go detects *.amazonaws.com and switches to
# virtual-host addressing + SigV4, so real AWS works with no code change.
# REGION IS NOT OPTIONAL in practice — empty costs a live bucket-location round
# trip and, if that fails, silently signs as us-east-1, producing presigned URLs
# that fail for whoever uses them with nothing server-side to trace it back to.
#S3_AWS_ENDPOINT=s3.eu-west-1.amazonaws.com
#S3_AWS_BUCKET=
#S3_AWS_REGION=eu-west-1
#S3_AWS_INSECURE=false
#S3_AWS_ACCESS_KEY=
#S3_AWS_SECRET_KEY=
EOF
  chmod 600 "$ENV_LOCAL"
fi

# ---------------------------------------------------------------------------
# 5. Fixtures + generated collection
# ---------------------------------------------------------------------------
"$SCRIPT_DIR/make-fixtures.sh" || die "fixture generation failed"

say "regenerating the Postman collection"
(cd "$TESTS_DIR" && node postman/build-collection.js) || die "collection build failed"

mkdir -p "$STATE_DIR" "$REPORT_DIR"

cat <<EOF

$(printf '%s' "$C_GRN")bootstrap complete$(printf '%s' "$C_OFF")

next:
  tests/scripts/deploy.sh                    # build + install the gateway unit
  tests/scripts/setup-minio.sh               # local object store + seed data
  tests/scripts/setup-vault.sh --seed        # seed the Vault secrets
  tests/scripts/fixtures-server.sh start     # fixture HTTP server for file_url
  tests/scripts/run-all.sh                   # the full regression

to enable the internal-MinIO and AWS backends, fill in $ENV_LOCAL
and re-run: node tests/postman/build-collection.js
EOF
